/**
 * Generates the service worker that makes this installable and offline.
 *
 * Hand-rolled rather than pulled from a plugin ecosystem, for the same reason the
 * fonts are fetched by a twenty-line script: what has to be cached here is unusual
 * and worth being explicit about. It is not a page and some images — it is a chess
 * engine and a SQLite build, about 2.6 MB of WebAssembly, and the app is useless
 * without either. Precaching them is the whole feature; a generic "cache what you
 * happen to visit" strategy would leave someone offline with no engine.
 *
 * The cache name carries a hash of the file list, so a new build takes over cleanly
 * and the old one's files are deleted rather than accumulating on a phone.
 */
import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { Plugin } from 'vite';

/** Big enough to matter, and everything here is needed before it can be used. */
function filesIn(dir: string, root = dir): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return filesIn(full, root);
    return [relative(root, full).split(/[\\/]/).join('/')];
  });
}

export function serviceWorker(): Plugin {
  let outDir = 'dist';
  let base = '/';

  return {
    name: 'chesscoach:service-worker',
    apply: 'build',

    configResolved(config) {
      outDir = config.build.outDir;
      base = config.base;
    },

    closeBundle() {
      const root = join(process.cwd(), outDir);

      const precache = filesIn(root)
        // Source maps are for whoever is debugging, not for a phone on a train.
        .filter((file) => !file.endsWith('.map'))
        .map((file) => `${base}${file}`)
        // The app is entered by its root, which is not a file in the build output.
        .concat(base);

      const version = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 12);

      writeFileSync(
        join(root, 'sw.js'),
        `/* Generated by web/plugins/service-worker.ts — do not edit. */
const CACHE = 'leaksheet-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  // Everything, before claiming to work offline. A half-cached engine is worse than
  // an honest failure, because it fails later and less clearly.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations are answered with the shell: the router is a client-side one, so
  // every path in the app is the same document.
  if (request.mode === 'navigate') {
    event.respondWith(caches.match(${JSON.stringify(base)}).then((hit) => hit || fetch(request)));
    return;
  }

  // Everything else is content-hashed or vendored, so a hit is always current.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          void caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`,
      );

      const bytes = precache
        .filter((file) => file !== base)
        .reduce((sum, file) => sum + statSync(join(root, file.slice(base.length))).size, 0);
      // eslint-disable-next-line no-console
      console.log(
        `  sw.js — precaching ${precache.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`,
      );
    },
  };
}
